"""Initialize and build an offline MkDocs site from workspace markdown."""

from __future__ import annotations

import html
import json
import os
import re
import shutil
import subprocess
from dataclasses import dataclass
from pathlib import Path

from skore_skills.workspace import is_scaffolded, package_name

CONFIG_NAME = "mkdocs.yml"
HTML_DIR = "html"
BUILD_DIR = Path("_build")
DOCS_DIR = BUILD_DIR / "docs"
GENERATED_CONFIG = BUILD_DIR / CONFIG_NAME
SITE_ASSETS = Path(__file__).with_name("site_assets")
STAGED_ASSETS = Path("assets") / "skore"
GITIGNORE_LINES = (f"{BUILD_DIR.as_posix()}/", f"{HTML_DIR}/")
MISSING_INDEX = "mkdocs build did not write html/index.html"
MISSING_MKDOCS = "mkdocs-material is required; add it with add-python-package"
ASSET_SUFFIXES = {".html", ".png", ".jpg", ".jpeg", ".svg", ".gif"}
MD_LINK = re.compile(r"\[([^\]]+)\]\(([^)]+)\)")
LINK = re.compile(r"(?<!!)\[([^\]]*)\]\(([^)\s]+)\)")
IMAGE_LINK = re.compile(
    r"(?<!!)\[([^\]]*)\]\(([^)\s]+\.(?:png|jpe?g|svg|gif))\)", re.IGNORECASE
)
RAW_IFRAME = re.compile(r'<iframe[^>]+src="([^"]+)"[^>]*>\s*</iframe>', re.IGNORECASE)
NOTEBOOKS_SECTION = re.compile(
    r"(?ms)^## Notebooks\s*\n.*?(?=^## |\Z)",
)
# Staged report pages measure themselves and post their height up, so the
# viewer fits the report exactly. Reading the document from the parent is
# blocked under ``file://``; postMessage is not. Measure the body box, not
# the root: the root stretches to the frame and would never shrink back.
HEIGHT_REPORTER = """<script>
(() => {
  const post = () => {
    const style = getComputedStyle(document.body);
    parent.postMessage(
      {
        type: "skore-embed-height",
        height: Math.ceil(
          document.body.getBoundingClientRect().height +
            parseFloat(style.marginTop) +
            parseFloat(style.marginBottom),
        ),
      },
      "*",
    );
  };
  addEventListener("load", post);
  new ResizeObserver(post).observe(document.body);
})();
</script>
"""


@dataclass(frozen=True)
class Page:
    """One Markdown report page in the generated site."""

    title: str
    source: Path
    dest_name: str
    notebook: Path | None = None
    section: str | None = None
    audit: Path | None = None


def _notebook_for(directory: Path, stem: str) -> Path | None:
    path = directory / f"{stem}.nb.html"
    return path if path.is_file() else None


def notebook_dest(page: Page) -> str:
    """Return the staged file name of the notebook page for ``page``."""
    return f"{Path(page.dest_name).stem}.nb.html"


def audit_dest(page: Page) -> str:
    """Return the staged file name of the audit notebook for ``page``."""
    return f"{Path(page.dest_name).stem}.audit.nb.html"


def collect_pages(root: Path) -> list[Page]:
    """Return Markdown report pages; notebooks are pages of their own."""
    pages: list[Page] = []
    journal = root / "journal" / "JOURNAL.md"
    if journal.is_file():
        pages.append(Page("Home", journal, "index.md"))
    analysis = root / "data_analysis" / "data_analysis.md"
    if analysis.is_file():
        pages.append(
            Page(
                "Exploratory data analysis",
                analysis,
                "data_analysis.md",
                _notebook_for(root / "data_analysis", "data_analysis"),
            )
        )
    notes = root / "journal"
    if notes.is_dir():
        for path in sorted(notes.glob("*.md")):
            if path.name in {"JOURNAL.md", "README.md"}:
                continue
            pages.append(
                Page(
                    path.stem,
                    path,
                    path.name,
                    _notebook_for(root / "experiments", path.stem),
                    "Experiments",
                    _notebook_for(root / "audit", path.stem),
                )
            )
    return pages


def site_title(root: Path) -> str:
    """Return the project name used as site title and launcher stem."""
    return package_name(root) or root.name


def launcher_name(root: Path) -> str:
    """Return the workspace-root HTML launcher filename."""
    return f"{site_title(root)}.html"


def render_launcher(title: str) -> str:
    """Return a ``file://``-safe redirect into ``html/index.html``."""
    safe = html.escape(title)
    return (
        "<!DOCTYPE html>\n"
        '<html lang="en">\n'
        "  <head>\n"
        '    <meta charset="utf-8">\n'
        f"    <title>{safe}</title>\n"
        '    <meta http-equiv="refresh" content="0; url=html/index.html">\n'
        '    <script>location.replace("html/index.html");</script>\n'
        "  </head>\n"
        "  <body>\n"
        f'    <p><a href="html/index.html">Open {safe}</a></p>\n'
        "  </body>\n"
        "</html>\n"
    )


def render_mkdocs_yml(
    pages: list[Page], *, stub_home: bool = False, site_name: str
) -> str:
    """Return generated ``mkdocs.yml`` text for ``file://`` browsing."""
    lines = [
        "# Generated by python -m skore_skills site build",
        f"site_name: {json.dumps(site_name)}",
        'site_url: ""',
        "use_directory_urls: false",
        "docs_dir: docs",
        "site_dir: ../html",
        "theme:",
        "  name: material",
        "  font: false",
        "  logo: assets/skore/skore-text.svg",
        "  favicon: assets/skore/favicon.svg",
        "extra:",
        "  polyfills:",
        "    - assets/skore/iframe-worker.js",
        "plugins:",
        "  - search",
        "  - offline",
        "extra_css:",
        "  - assets/skore/skore.css",
        "extra_javascript:",
        "  - assets/skore/nav-data.js",
        "  - assets/skore/skore.js",
        "nav:",
    ]
    if stub_home and not any(page.dest_name == "index.md" for page in pages):
        lines.append("  - Home: index.md")
    if pages:
        sections: dict[str, list[Page]] = {}
        for page in pages:
            if page.section is None:
                lines.append(f"  - {page.title}: {page.dest_name}")
            else:
                sections.setdefault(page.section, []).append(page)
        for title, children in sections.items():
            lines.append(f"  - {title}:")
            lines.extend(f"      - {page.title}: {page.dest_name}" for page in children)
    elif not stub_home:
        lines.append("  - Home: index.md")
    lines.append("")
    return "\n".join(lines)


def write_generated_config(root: Path, pages: list[Page], *, stub_home: bool) -> Path:
    """Write ``_build/mkdocs.yml`` for this build."""
    dest = root / GENERATED_CONFIG
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(
        render_mkdocs_yml(pages, stub_home=stub_home, site_name=site_title(root)),
        encoding="utf-8",
    )
    return dest


def ensure_site_gitignore(root: Path) -> None:
    """Append ``_build/``, ``html/``, and the root launcher to ``.gitignore``."""
    gitignore = root / ".gitignore"
    existing = gitignore.read_text(encoding="utf-8") if gitignore.is_file() else ""
    present = {line.strip() for line in existing.splitlines()}
    wanted = (*GITIGNORE_LINES, launcher_name(root))
    additions = [line for line in wanted if line not in present]
    if not additions:
        return
    prefix = "" if not existing or existing.endswith("\n") else "\n"
    gitignore.write_text(
        existing + prefix + "\n".join(additions) + "\n", encoding="utf-8"
    )


def rewrite_markdown_links(text: str, dest_names: set[str]) -> str:
    """Point Markdown links at files that exist in the flattened docs tree."""

    def replace(match: re.Match[str]) -> str:
        label, url = match.group(1), match.group(2)
        if url.startswith(("#", "http:", "https:", "mailto:")):
            return match.group(0)
        path, sep, rest = url.partition("#")
        if not path:
            return match.group(0)
        path, qsep, query = path.partition("?")
        name = Path(path).name
        if name in dest_names or Path(name).suffix.lower() in ASSET_SUFFIXES:
            return f"[{label}]({name}{qsep}{query}{sep}{rest})"
        return match.group(0)

    return MD_LINK.sub(replace, text)


def render_embed(name: str, title: str, *, autosize: bool = False) -> str:
    """Return an accessible, fullscreen-capable HTML viewer."""
    safe_name = html.escape(name, quote=True)
    safe_title = html.escape(title)
    sizing = " data-skore-autosize" if autosize else ""
    return (
        f'<div class="skore-embed" data-skore-embed>\n'
        f'  <div class="skore-embed__toolbar">\n'
        f'    <span class="skore-embed__title">{safe_title}</span>\n'
        f'    <div class="skore-embed__actions">\n'
        f'      <a class="skore-button" href="{safe_name}" target="_blank" '
        f'rel="noopener">Open separately</a>\n'
        f'      <button class="skore-button" type="button" '
        f'data-skore-fullscreen aria-pressed="false">\n'
        f'        <svg viewBox="0 0 24 24" aria-hidden="true">'
        f'<path d="M7 3H3v4h2V5h2V3zm12 4h2V3h-4v2h2v2zM5 17H3v4h4v-2H5v-2z'
        f'm14 2h-2v2h4v-4h-2v2z"/></svg>\n'
        f'        <span class="skore-button__label">Full screen</span>\n'
        f"      </button>\n"
        f"    </div>\n"
        f"  </div>\n"
        f'  <iframe src="{safe_name}" title="{safe_title}" '
        f'loading="lazy"{sizing}></iframe>\n'
        f"</div>"
    )


def embed_assets(text: str) -> str:
    """Render asset links inline: images as embeds, HTML in viewers."""
    seen = set(RAW_IFRAME.findall(text))
    text = RAW_IFRAME.sub(
        lambda match: render_embed(match.group(1), "Interactive report", autosize=True),
        text,
    )
    embedded: list[str] = []
    for line in text.splitlines():
        embedded.append(IMAGE_LINK.sub(r"![\1](\2)", line))
        for match in LINK.finditer(line):
            name = match.group(2)
            if Path(name).suffix.lower() != ".html" or name in seen:
                continue
            seen.add(name)
            embedded.extend(
                ["", render_embed(name, "Interactive report", autosize=True)]
            )
    return "\n".join(embedded) + "\n"


def inject_notebook(text: str, page: Page) -> str:
    """Insert paired experiment viewers or append one analysis viewer."""
    if page.section == "Experiments":
        viewers: list[str] = []
        for source, heading, name in (
            (page.notebook, "Evaluation notebook", notebook_dest(page)),
            (page.audit, "Audit notebook", audit_dest(page)),
        ):
            if source is None:
                continue
            embed = render_embed(name, f"{page.title} {heading.lower()}")
            viewers.append(f"### {heading}\n\n{embed}")

        section = "## Notebooks\n"
        if viewers:
            section += "\n" + "\n\n".join(viewers) + "\n"

        if NOTEBOOKS_SECTION.search(text):
            return NOTEBOOKS_SECTION.sub(section, text, count=1)
        if not viewers:
            return text
        return f"{text.rstrip()}\n\n{section}"

    for source, heading, name in (
        (page.notebook, "Notebook", notebook_dest(page)),
        (page.audit, "Audit", audit_dest(page)),
    ):
        if source is None or f'src="{name}"' in text:
            continue
        if not text.endswith("\n"):
            text += "\n"
        embed = render_embed(name, f"{page.title} {heading.lower()}")
        text = f"{text}\n## {heading}\n\n{embed}\n"
    return text


def with_height_reporter(text: str) -> str:
    """Return report HTML that posts its content height to the viewer."""
    index = text.lower().rfind("</body>")
    if index == -1:
        return text + HEIGHT_REPORTER
    return text[:index] + HEIGHT_REPORTER + text[index:]


def _copy_data_analysis_assets(root: Path, docs: Path) -> None:
    analysis = root / "data_analysis"
    if not analysis.is_dir():
        return
    for path in analysis.iterdir():
        if path.name.endswith(".nb.html") or not path.is_file():
            continue
        if path.suffix.lower() == ".html":
            (docs / path.name).write_text(
                with_height_reporter(path.read_text(encoding="utf-8")),
                encoding="utf-8",
            )
        elif path.suffix.lower() in ASSET_SUFFIXES:
            shutil.copy2(path, docs / path.name)


def _write_stub_index(docs: Path) -> bool:
    dest = docs / "index.md"
    if dest.is_file():
        return False
    dest.write_text("# Report\n", encoding="utf-8")
    return True


def _copy_notebook(src: Path, dest: Path) -> None:
    shutil.copy2(src, dest)


def _copy_site_assets(docs: Path) -> None:
    shutil.copytree(SITE_ASSETS, docs / STAGED_ASSETS)


def write_nav_data(docs: Path, pages: list[Page], *, stub_home: bool) -> Path:
    """Write top-navigation data as JavaScript that works under ``file://``."""
    items: list[dict[str, object]] = []
    if stub_home and not any(page.dest_name == "index.md" for page in pages):
        items.append({"label": "Home", "href": "index.html"})
    sections: dict[str, list[dict[str, object]]] = {}
    for page in pages:
        item: dict[str, object] = {
            "label": page.title,
            "href": Path(page.dest_name).with_suffix(".html").as_posix(),
        }
        if page.section is None:
            items.append(item)
        else:
            sections.setdefault(page.section, []).append(item)
    items.extend(
        {"label": title, "children": children} for title, children in sections.items()
    )
    dest = docs / STAGED_ASSETS / "nav-data.js"
    dest.write_text(
        f"window.__SKORE_NAV__ = {json.dumps(items, ensure_ascii=False)};\n",
        encoding="utf-8",
    )
    return dest


def stage_docs(root: Path) -> tuple[Path, list[Page], bool]:
    """Copy report Markdown, assets, and existing companions into ``_build/docs``.

    Returns
    -------
    tuple
        Staging directory, collected pages, and whether a stub home was written.
    """
    docs = root / DOCS_DIR
    if docs.exists():
        shutil.rmtree(docs)
    docs.mkdir(parents=True)
    pages = collect_pages(root)
    dest_names = {page.dest_name for page in pages}
    dest_names.add("index.md")
    for page in pages:
        text = rewrite_markdown_links(
            page.source.read_text(encoding="utf-8"), dest_names
        )
        text = inject_notebook(embed_assets(text), page)
        (docs / page.dest_name).write_text(text, encoding="utf-8")
        if page.notebook is not None:
            _copy_notebook(page.notebook, docs / notebook_dest(page))
        if page.audit is not None:
            _copy_notebook(page.audit, docs / audit_dest(page))
    _copy_data_analysis_assets(root, docs)
    _copy_site_assets(docs)
    stub_home = _write_stub_index(docs)
    write_nav_data(docs, pages, stub_home=stub_home)
    return docs, pages, stub_home


def init_site(root: Path, *, force: bool = False) -> Path:
    """Ignore site build directories. Does not write a user ``mkdocs.yml``.

    Parameters
    ----------
    root : pathlib.Path
        Workspace root.
    force : bool, optional
        Unused; kept so existing ``--force`` callers stay valid.

    Raises
    ------
    ValueError
        When the workspace is not scaffolded.
    """
    del force
    if not is_scaffolded(root):
        raise ValueError("workspace is not scaffolded")
    ensure_site_gitignore(root)
    gitignore = root / ".gitignore"
    gitignore.touch()
    return gitignore


def build_site(root: Path) -> str:
    """Stage sources, write ``_build/mkdocs.yml``, and run ``mkdocs build``.

    Raises
    ------
    ValueError
        When the workspace is not scaffolded.
    RuntimeError
        When ``mkdocs`` is missing, the build fails, or ``index.html`` is missing.
    """
    if not is_scaffolded(root):
        raise ValueError("workspace is not scaffolded")
    ensure_site_gitignore(root)
    _docs, pages, stub_home = stage_docs(root)
    write_generated_config(root, pages, stub_home=stub_home)
    try:
        completed = subprocess.run(
            ["mkdocs", "build", "--config-file", os.fspath(GENERATED_CONFIG)],
            cwd=root,
            check=False,
            capture_output=True,
            text=True,
        )
    except FileNotFoundError as exc:
        raise RuntimeError(MISSING_MKDOCS) from exc
    if completed.returncode:
        detail = (completed.stderr or completed.stdout or "mkdocs build failed").strip()
        raise RuntimeError(detail)
    index = root / HTML_DIR / "index.html"
    if not index.is_file():
        raise RuntimeError(MISSING_INDEX)
    launcher = root / launcher_name(root)
    launcher.write_text(render_launcher(site_title(root)), encoding="utf-8")
    extra = (completed.stdout or "").strip()
    if extra:
        return f"{extra}\n{launcher}"
    return str(launcher)
